title: The Plausible Blog
baseurl: /blog/
permalink: /:title
highlighter: rouge
url: https://plausible.io
description: 'Stories, learnings and experiences gained from building an open source privacy-friendly Google Analytics alternative'

show_excerpts: true

plugins:
 - jekyll-feed
 - jekyll-seo-tag
