name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/jekyll:latest /bin/bash -c "chmod -R 777 /srv/jekyll && npm install && jekyll build --future"

    - name: rsync deployment
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: _site/
        remote_path: /var/www/html/
        remote_host: web.plausible.io
        remote_user: root
        remote_key: ${{ secrets.DEPLOY_KEY }}
